#!/usr/bin/env zsh


source /usr/share/zsh/plugins/fast-syntax-highlighting/fast-syntax-highlighting.plugin.zsh 2>/dev/null
source /usr/share/zsh/plugins/zsh-system-clipboard/zsh-system-clipboard.zsh 2>/dev/null
source $XDG_CONFIG_HOME/nix-zsh-plugins.zsh 2>/dev/null

LS_COLORS=$LS_COLORS:'di=1;36:'
export LS_COLORS
