#!/usr/bin/zsh

LS_COLORS=$LS_COLORS:'di=1;36:'
export LS_COLORS

source /usr/share/zsh/plugins/fast-syntax-highlighting/fast-syntax-highlighting.plugin.zsh 2>/dev/null


# Override highlighter colors
FAST_HIGHLIGHT_STYLES[alias]=fg=none
FAST_HIGHLIGHT_STYLES[default]=fg=none
FAST_HIGHLIGHT_STYLES[builtin]=fg=none
FAST_HIGHLIGHT_STYLES[precommand]=fg=none
FAST_HIGHLIGHT_STYLES[command]=fg=none
FAST_HIGHLIGHT_STYLES[commandseparator]=none
FAST_HIGHLIGHT_STYLES[unknown-token]=fg=red,bold
FAST_HIGHLIGHT_STYLES[reserver-word]=fg=red,bold
FAST_HIGHLIGHT_STYLES[assign]=none
FAST_HIGHLIGHT_STYLES[history-expansion]=none
FAST_HIGHLIGHT_STYLES[single-hyphen-option]=none
FAST_HIGHLIGHT_STYLES[double-hyphen-option]=none
FAST_HIGHLIGHT_STYLES[single-quoted-argument]=none
FAST_HIGHLIGHT_STYLES[double-quoted-argument]=none
FAST_HIGHLIGHT_STYLES[path]=none
FAST_HIGHLIGHT_STYLES[path-to-dir]=none

man() {
    LESS="-N" \
    LESS_TERMCAP_md=$'\e[01;31m' \
    LESS_TERMCAP_me=$'\e[0m' \
    LESS_TERMCAP_so=$'\e[01;44;33m' \
    LESS_TERMCAP_se=$'\e[0m' \
    LESS_TERMCAP_us=$'\e[01;32m' \
    LESS_TERMCAP_ue=$'\e[0m' \
    command man "$@"
}


source /usr/share/zsh/plugins/zsh-system-clipboard/zsh-system-clipboard.zsh 2>/dev/null

