#!/bin/sh

export PATH="$PATH:$(du "$HOME/.local/bin"| cut -f2 | tr '\n' ':')"
export PATH="$PATH:$HOME/.local/share/cargo/bin"
export PATH="$PATH:$HOME/.local/share/firefox"

# Default Programs:
export EDITOR="nvim"
export TERMINAL="st"
export BROWSER="firefox"

# ~/ Clean-up: XDG-Base-Directory Specs.
export XDG_SESSION_TYPE="x11"
export XDG_CONFIG_HOME="$HOME/.config"
export XDG_CACHE_HOME="$HOME/.cache"
export XDG_LOCAL_HOME="$HOME/.local"
export XDG_STATE_HOME="$HOME/.local/state"
export XDG_DATA_HOME="$HOME/.local/share"
export XDG_PUBLICSHARE_DIR="$HOME/Cloud"
export XDG_DOWNLOAD_DIR="$HOME/Downloads"
export XDG_DOTFILES="$HOME/dots"

# Shell:
export ZDOTDIR="$XDG_CONFIG_HOME/zsh"
export XINITRC="$XDG_CONFIG_HOME/X11/xinitrc"
export XAUTHORITY="$XDG_RUNTIME_DIR/Xauthority"
export PASSWORD_STORE_DIR="$XDG_DATA_HOME/password-store"
export GNUPGHOME="$XDG_DATA_HOME/gnupg"

# Python / Jupyter:
export IPYTHONDIR="$XDG_CONFIG_HOME/jupyter"
export JUPYTER_CONFIG_DIR="$XDG_CONFIG_HOME/jupyter"
export JP_LSP_VIRTUAL_DIR="$XDG_CACHE_HOME/jupyter/"
export PYTHONSTARTUP="$XDG_CONFIG_HOME/python/pythonrc"
export PYTHON_HISTORY="$XDG_STATE_HOME/python_history"

# Julia
export JULIA_DEPOT_PATH="$XDG_DATA_HOME/julia:$JULIA_DEPOT_PATH"
export JULIA_HISTORY="$XDG_CACHE_HOME/julia/history.jl"

# Rust
export CARGO_HOME="$XDG_DATA_HOME/cargo"
export RUSTUP_HOME="$XDG_DATA_HOME"/rustup
export FOUNDRY_DISABLE_NIGHTLY_WARNING=true

# Man Config
export LESSHISTFILE=-
export MANPAGER='nvim +Man!'
export MANROFFOPT="-P -c"

# GTK / QT:
export GTK_THEME=Adwaita-dark
export GTK2_RC_FILES=/usr/share/themes/Adwaita-dark/gtk-2.0/gtkrc
export QT_STYLE_OVERRIDE=adwaita-dark.

# Node.js / NPM / BUN config:
export NODE_REPL_HISTORY="$XDG_DATA_HOME"/node_repl_history
export BUN_INSTALL="$XDG_CONFIG_HOME/bun"
export NPM_CONFIG_USERCONFIG=$XDG_CONFIG_HOME/npm/npmrc

# JAVA
export _JAVA_OPTIONS=-Djava.util.prefs.userRoot="$XDG_CONFIG_HOME"/java
export _JAVA_AWT_WM_NONREPARENTING=1
export JAVA_HOME=/usr/lib/jvm/default

# Android dev:
export GRADLE_USER_HOME="$XDG_DATA_HOME"/gradle
export ANDROID_HOME=$XDG_DATA_HOME/Android/SDK/
export PATH=$PATH:$ANDROID_HOME/emulator
export PATH=$PATH:$ANDROID_HOME/platform-tools

# Other:
export NOTMUCH_CONFIG="$XDG_CONFIG_HOME/notmuch-config"
export W3M_DIR="$XDG_STATE_HOME/w3m"
export SSB_HOME="$XDG_DATA_HOME/zoom"
export WGETRC="$XDG_CONFIG_HOME/wgetrc"
export PGPLOT_FONT='/usr/lib/grfont.dat'
export PGSERVICEFILE="$XDG_CONFIG_HOME/pg/pg_service.conf"
export ELECTRUMDIR="$XDG_DATA_HOME/electrum"
