#!/bin/sh

export PATH="$PATH:$(du "$HOME/.local/bin"| cut -f2 | tr '\n' ':')"
export PATH="$PATH:$HOME/.local/share/cargo/bin"
export PATH="$PATH:$HOME/.local/share/firefox"

# Default Programs:
export EDITOR="nvim"
export TERMINAL="st"
export BROWSER="firefox"

# ~/ Clean-up: XDG-Base-Directory Specs.
export XDG_SESSION_TYPE="x11"
export XDG_CONFIG_HOME="$HOME/.config"
export XDG_CACHE_HOME="$HOME/.cache"
export XDG_LOCAL_HOME="$HOME/.local"
export XDG_STATE_HOME="$HOME/.local/state"
export XDG_DATA_HOME="$HOME/.local/share"
export XDG_PUBLICSHARE_DIR="$HOME/Cloud"
export XDG_DOWNLOAD_DIR="$HOME/Downloads"


export __ETC_ZSHRC_SOURCED=1
export __ETC_ZSHENV_SOURCED=1
export NOSYSZSHRC=1
export ZDOTDIR="$XDG_CONFIG_HOME/zsh"
export RANGER_DEVICONS_SEPARATOR="  "
export CARGO_HOME="$XDG_DATA_HOME/cargo"
export ELECTRUMDIR="$XDG_DATA_HOME/electrum"
export GNUPGHOME="$XDG_DATA_HOME/gnupg"
export HISTFILE="$XDG_DATA_HOME/zsh/history"
export IPYTHONDIR="$XDG_CONFIG_HOME/jupyter"
export JULIA_DEPOT_PATH="$XDG_DATA_HOME/julia:$JULIA_DEPOT_PATH"
export JULIA_HISTORY="$XDG_CACHE_HOME/julia/history.jl"
export JUPYTER_CONFIG_DIR="$XDG_CONFIG_HOME/jupyter"
export LESSHISTFILE=-
export NOTMUCH_CONFIG="$XDG_CONFIG_HOME/notmuch-config"
export NPM_CONFIG_USERCONFIG=$XDG_CONFIG_HOME/npm/npmrc
export PASSWORD_STORE_DIR="$XDG_DATA_HOME/password-store"
export PYTHONSTARTUP="$XDG_CONFIG_HOME/python/pythonrc"
export PYTHON_HISTORY="$XDG_STATE_HOME/python_history"
export SSB_HOME="$XDG_DATA_HOME/zoom"
export WGETRC="$XDG_CONFIG_HOME/wgetrc"
export XAUTHORITY="$XDG_RUNTIME_DIR/Xauthority"
export XINITRC="$XDG_CONFIG_HOME/X11/xinitrc"
export _JAVA_AWT_WM_NONREPARENTING=1
export PGPLOT_FONT='/usr/lib/grfont.dat'
export RUSTUP_HOME="$XDG_DATA_HOME"/rustup
export MANPAGER='nvim +Man!'
export MANROFFOPT="-P -c"
export GTK_THEME=Adwaita-dark
export GTK2_RC_FILES=/usr/share/themes/Adwaita-dark/gtk-2.0/gtkrc
export QT_STYLE_OVERRIDE=adwaita-dark.
export WINEPREFIX="$XDG_DATA_HOME"/wineprefixes/default
export JP_LSP_VIRTUAL_DIR="$XDG_CACHE_HOME/jupyter/"
export NODE_REPL_HISTORY="$XDG_DATA_HOME"/node_repl_history
export BUN_INSTALL="$XDG_CONFIG_HOME/bun"
export FOUNDRY_DISABLE_NIGHTLY_WARNING=true
export _JAVA_OPTIONS=-Djava.util.prefs.userRoot="$XDG_CONFIG_HOME"/java
export W3M_DIR="$XDG_STATE_HOME/w3m"
export PGSERVICEFILE="$XDG_CONFIG_HOME/pg/pg_service.conf"
