#!/bin/sh

if [[ -z "$DBUS_SESSION_BUS_ADDRESS" ]]; then
    export $(dbus-launch --exit-with-x11)
fi

if (( $(xrandr | grep " connected "| wc -l) == 3 ));then
    export MONITOR_OUT=1
    edid_mulmon
    set_kb_mouse
else
    export MONITOR_OUT=0
    xrdb $XDG_CONFIG_HOME/X/Xresources &
fi

monitor_recon &\
xset r rate 300 50 &\
xset mouse 1.8 0 &\
setxkbmap -model p104 -layout us,de -option grp:shifts_toggle &\
dbus-update-activation-environment --systemd DBUS_SESSION_BUS_ADDRESS DISPLAY XAUTHORITY &\
down redshift & redshift -l $(curl ipinfo.io/loc | sed "s/,/:/") &\

xidlehook \
    --not-when-fullscreen \
    --not-when-audio\
    --timer 300 \
        'slock' \
        '' \
    --timer 900 \
        'systemctl suspend-then-hibernate' \
        '' &

dunst &\
xcompmgr &\
nextcloud --background &\
dwmblocks &

if [[ $(cat /sys/class/power_supply/ACAD/online) == "1" ]] then
    sudo powerprofilesctl set performance &
else
    sudo powerprofilesctl set balanced &
fi
